import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../shared/styles/globals.css";
import UIProviders from "@/shared/utils/UIProvider";
import StateProviders from "@/shared/utils/StateProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateProviders>
          <UIProviders>
            {children}
          </UIProviders>
        </StateProviders>
      </body>
    </html>
  );
}
